// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiPondOrderSystemManagement.Repositories.Models;

public partial class CustomerHistory
{
    public int HistoryId { get; set; }

    public int CustomerId { get; set; }

    public string OrderType { get; set; }

    public int OrderId { get; set; }

    public DateTime OrderDate { get; set; }

    public string OrderStatus { get; set; }

    public decimal? TotalCost { get; set; }

    public int? Rating { get; set; }

    public string Feedback { get; set; }

    public virtual User Customer { get; set; }
}