// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace KoiPondOrderSystemManagement.Repositories.Models;

public partial class User
{
    public int UserId { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public string Address { get; set; }

    public string Role { get; set; }

    public string PasswordHash { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    public string Gender { get; set; }

    public bool Status { get; set; }

    public virtual ICollection<CustomerHistory> CustomerHistories { get; set; } = new List<CustomerHistory>();

    public virtual ICollection<Feedback> Feedbacks { get; set; } = new List<Feedback>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual ICollection<Pond> PondConsultingStaffs { get; set; } = new List<Pond>();

    public virtual ICollection<Pond> PondCustomers { get; set; } = new List<Pond>();

    public virtual ICollection<Pond> PondDesignStaffs { get; set; } = new List<Pond>();

    public virtual ICollection<Service> ServiceCustomers { get; set; } = new List<Service>();

    public virtual ICollection<Service> ServiceStaffs { get; set; } = new List<Service>();
}